apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: hasura-with-obs
data:
  ES_JAVA_OPTS: -Xms256m -Xmx256m
  discovery.type: single-node
  discovery.seed_hosts : "[\"localhost\", \"127.0.0.1\"]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: hasura-with-obs
  labels:
    app: elk-logging
spec:
  # serviceName: elk-logging
  replicas: 1
  # updateStrategy:
  #   type: RollingUpdate
  selector:
    matchLabels:
      app: elk-logging
  template:
    metadata:
      labels:
        app: elk-logging
    spec:
      serviceAccountName: elk-logging
      containers:
      - image: elasticsearch:7.17.18
        name: elastic
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elastic
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: discovery.type
          valueFrom:
              configMapKeyRef:
                  name: elastic-config
                  key: discovery.type
        - name: discovery.seed_hosts
          valueFrom:
              configMapKeyRef:
                  name: elastic-config
                  key: discovery.seed_hosts
      volumes:
      - name: elastic
        emptyDir: {}
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elastic-init
        securityContext:
          privileged: true