apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: hasura-with-obs
  labels:
    app: elk-logging
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    app: elk-logging