apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: hasura-with-obs
  labels:
    app: hasura
    logging: "promtail"
    logging_jobname: "graphql-engine"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
        logging: "promtail"
        logging_jobname: "graphql-engine"
    spec:
      containers:
        - name: graphql-engine
          image: hasura/graphql-engine:v2.28.0
          ports:
            - containerPort: 8080
          readinessProbe:
              httpGet:
                path: /healthz
                port: 443
                scheme: HTTPS
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
          livenessProbe:
              httpGet:
                path: /healthz
                port: 443
                scheme: HTTPS
              initialDelaySeconds: 20
              periodSeconds: 10
              timeoutSeconds: 5
          envFrom:
          - configMapRef:
              name: hasura-config
          - secretRef:
              name: hasura-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hasura-service
  namespace: hasura-with-obs
  labels:
    app: hasura
    namespace: hasura-with-obs
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hasura