apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: data-as-a-service-hl-global
  labels:
    app: hasura
    logging: "promtail"
    logging_jobname: "graphql-engine"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
        logging: "promtail"
        logging_jobname: "graphql-engine"
    spec:
      # serviceAccountName: data-as-a-service-hl-global-svc-acct
      containers:
        - name: promtail
          image: grafana/promtail:2.8.2
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: promtail-configfile
              mountPath: /etc/promtail
            - name: logs
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: stdout-logfile-path
              mountPath: /var/log/hge-pro
              readOnly: true
          args:
            - -config.file
            - /etc/promtail/promtail-config-k8s.yml
        - name: graphql-engine
          image: hasura/graphql-engine:v2.28.0
          command: ["/bin/sh"]
          args: ["-c", "\"${HGE_BINARY}\" serve 2>&1 | tee >(split -d -b 100000 /var/log/hge-pro/hge-pro-ds.log -)"]
          volumeMounts:
            - name: stdout-logfile-path
              mountPath: /var/log/hge-pro
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: hasura-config
          - secretRef:
              name: hasura-secret
      volumes:
        - name: promtail-configfile
          hostPath:
            path: /hosthome/promtail/etc
            type: Directory
        - name: logs
          hostPath:
            path: /var/log
        - name: stdout-logfile-path
          hostPath:
            path: /hosthome/logs/var/log/hge-pro
            type: Directory
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: hasura-service
  namespace: data-as-a-service-hl-global
  labels:
    app: hasura
    namespace: data-as-a-service-hl-global
spec:
  type: NodePort
  ports:
    - name: hge-port
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: promtail-port
      port: 9080
      targetPort: 9080
      nodePort: 30908
  selector:
    app: hasura