apiVersion: v1
kind: Secret
metadata:
  name: hasura-secrets
type: Opaque
data:
  HASURA_GRAPHQL_METADATA_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc3B3QHBvc3RncmVzOjU0MzIvaGFzdXJhZGI=
  PG_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc3B3QHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ==
  HASURA_GRAPHQL_JWT_SECRET: J3sidHlwZSI6IkhTMjU2IiwgImtleSI6ICJqd3Rfc2VjcmV0Lmp3dF9zZWNyZXQuand0X3NlY3JldC5qd3Rfc2VjcmV0Lmp3dF9zZWNyZXQifSc=