apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: hasura-with-obs
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [kubernetes][container][name] == "graphql-engine" {
        grok {
          match => { "message" => "%{COMBINEDAPACHELOG}" }
        }
        date {
          match => [ "timestamp" , "ISO8601", "yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
        }
        if "http-log" in [message] or "query-log in [message]" {
          json {
            source => "message"
            target => "hasura.log"
          }
          if "query-log" in [message] {
            mutate {
              convert => { "hasura.log.detail.generated_sql.friends.prepared_arguments" => "integer" }
            }
          }
        }
      } else {
        grok {
            match => { "message" => "%{COMBINEDAPACHELOG}" }
        }
        date {
          match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
        }
      }
      geoip {
        source => "clientip"
      }
    }
    output {
      elasticsearch {
        hosts => ["elastic-service:9200"]
      }
    }