apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: hasura-with-obs
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.4.0
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-configfile
              mountPath: /etc/loki
          args:
            - -config.file=/etc/loki/loki-config.yml
      volumes:
        - name: loki-configfile
          hostPath:
            path: /hosthome/loki/etc
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: hasura-with-obs
  labels:
    app: loki
    namespace: hasura-with-obs
spec:
  type: NodePort
  ports:
    - name: loki-port
      port: 3100
      targetPort: 3100
      nodePort: 30310
  selector:
    app: loki