apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: hasura-with-obs
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        containers:
        - name: loki
          image: grafana/loki:2.4.0
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: hasura-with-obs
  labels:
    app: loki
    namespace: hasura-with-obs
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki