apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hasura-with-obs
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: postgres-secret
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          hostPath:
            path: /hosthome/postgres
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: hasura-with-obs
  labels:
    app: postgres
    namespace: hasura-with-obs
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30543
  selector:
    app: postgres