apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: hasura-with-obs
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
    - job_name: kube_pod_promtail_scrape
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
        - source_labels: ["__meta_docker_container_label_logging_jobname"]
          target_label: "job"
        - source_labels: [__meta_kubernetes_pod_container_name]
          regex: "/(.*)"
          target_label: "instance"
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod_name
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace