apiVersion: v1
kind: Deployment
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        containers:
        - name: promtail
          image: grafana/promtail:2.8.2
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: promtail-configfile
              mountPath: /etc/promtail
      volumes:
        - name: promtail-configfile
          hostPath:
            path: /home/widya/works/github/hasura/promtail/etc
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app: promtail
    namespace: hasura-with-obs
spec:
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: promtail