server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-service.hasura-with-obs.svc.cluster.local:3100/loki/api/v1/push

scrape_configs:
# kubernetes pod logs
  # - job_name: kubernetes-pods
  #   kubernetes_sd_configs:
  #   - role: pod
  #   relabel_configs:
  #   - source_labels:
  #     - __meta_kubernetes_pod_node_name
  #     target_label: __host__
  #   - action: drop
  #     regex: ^$
  #     source_labels:
  #     - __meta_kubernetes_pod_label_name
  #   - action: replace
  #     replacement: $1
  #     separator: /
  #     source_labels:
  #     - __meta_kubernetes_namespace
  #     - __meta_kubernetes_pod_label_name
  #     target_label: job
  #   - action: replace
  #     source_labels:
  #     - __meta_kubernetes_namespace
  #     target_label: namespace
  #   - action: replace
  #     source_labels:
  #     - __meta_kubernetes_pod_name
  #     target_label: instance
  #   - action: replace
  #     replacement: /var/log/pods/*$1/*.log
  #     regex: true/(.*)
  #     separator: /
  #     source_labels:
  #       - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
  #       - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
  #       - __meta_kubernetes_pod_container_name
  #     target_label: __path__
  #   - action: replace
  #     replacement: var/log/pods/*$1/*.log
  #     separator: /
  #     source_labels:
  #     - __meta_kubernetes_pod_uid
  #     - __meta_kubernetes_pod_container_name
  #     target_label: __path__
  # - job_name: kubernetes-pods-app
  #   kubernetes_sd_configs:
  #   - role: pod
  #   relabel_configs:
  #   - source_labels:
  #     - __meta_kubernetes_pod_node_name
  #     target_label: __host__
  #   - action: drop
  #     regex: ^$
  #     source_labels:
  #     - __meta_kubernetes_pod_label_app
  #   - action: replace
  #     replacement: $1
  #     separator: /
  #     source_labels:
  #     - __meta_kubernetes_namespace
  #     - __meta_kubernetes_pod_label_app
  #     target_label: job
  #   - action: replace
  #     source_labels:
  #     - __meta_kubernetes_namespace
  #     target_label: namespace
  #   - action: replace
  #     source_labels:
  #     - __meta_kubernetes_pod_name
  #     target_label: instance
  #   - action: labelmap
  #     regex: __meta_kubernetes_pod_label_(.+)
  #   - replacement: /var/log/pods/$1
  #     separator: /
  #     source_labels:
  #     - __meta_kubernetes_pod_uid
  #     - __meta_kubernetes_pod_container_name
  #     target_label: __path__
# local machine logs
  - job_name: local
    static_configs:
    - targets:
        - localhost
      labels:
        job: hasura
        __path__: /var/log/**/*.log
    pipeline_stages:
    - replace:
        expression: '\"{'
        replace: '{'
    - replace:
        expression: '}\\n\"'
        replace: '}'
    - replace:
        expression: '\\\"'
        replace: '"'
# # docker logs
# - job_name: flog_scrape
#   docker_sd_configs:
#     - host: unix:///var/run/docker.sock
#       refresh_interval: 5s
#       filters:
#         - name: label
#           values: ["logging=promtail"]
#   relabel_configs:
#     - source_labels: ["__meta_docker_container_name"]
#       regex: "/(.*)"
#       target_label: "instance"
#     - source_labels: ["__meta_docker_container_label_logging_jobname"]
#       target_label: "job"
  
## docker logs

# - job_name: docker 
#   pipeline_stages:
#     - docker: {}
#   static_configs:
#     - labels:
#         job: docker
#         __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

# - job_name: syslog
#   syslog:
#     listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#     idle_timeout: 60s
#     label_structured_data: yes
#   labels:
#     job: "syslog"
#   relabel_configs:
#     - source_labels: ['__syslog_message_hostname']
#       target_label: 'host'