server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.192.1:3100/loki/api/v1/push

scrape_configs:
# local machine logs
- job_name: local
  static_configs:
  - targets:
      - http://192.168.192.1
    labels:
      job: hasura
      __path__: /home/widya/works/github/hasura/hasura/logs/*.log
- job_name: flog_scrape
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: label
          values: ["logging=promtail"]
  relabel_configs:
    - source_labels: ["__meta_docker_container_name"]
      regex: "/(.*)"
      target_label: "instance"
    - source_labels: ["__meta_docker_container_label_logging_jobname"]
      target_label: "job"
  
## docker logs

# - job_name: docker 
#   pipeline_stages:
#     - docker: {}
#   static_configs:
#     - labels:
#         job: docker
#         __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

# - job_name: syslog
#   syslog:
#     listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#     idle_timeout: 60s
#     label_structured_data: yes
#   labels:
#     job: "syslog"
#   relabel_configs:
#     - source_labels: ['__syslog_message_hostname']
#       target_label: 'host'