server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-service.data-as-a-service-hl-global.svc.cluster.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: local
    static_configs:
    - targets:
        - localhost
      labels:
        job: hasura
        __path__: /var/log/hge-pro/hge-pro-ds.log
    pipeline_stages:
    - replace:
        expression: '\"{'
        replace: '{'
    - replace:
        expression: '}\\n\"'
        replace: '}'
    - replace:
        expression: '\\\"'
        replace: '"'